### ISSUE TITLE
在楼中楼回复机器人(带回复账号)时机器人回复循环的问题

### ISSUE THREAD

**Issue by CoolSpring8** [giuem/TieBaRobot#1]
不好意思，描述得不是很清晰，请看http://tieba.baidu.com/p/3594653645 此贴的二楼。
对于用户而言，目前临时的解决办法:在机器人系统里把那些用来回帖的小号都添加到回复黑名单里，理论上这样就不会循环了。
其实也可以在代码层面上把用来回复的小号的回复自动忽略吧。

**Comment by giuem** [comment]
Yep.You can make it by youself.I have no time.Sorry..
