### ISSUE TITLE
求一份robot的使用说明。

### ISSUE THREAD

**Issue by sadk** [giuem/TieBaRobot#2]
不太懂安装之后怎么设置。可以自行定制接口的吧？

**Comment by sadk** [comment]
求一份设置文档

**Comment by giuem** [comment]
对不起，暂时没有说明，我没有写插件机制。。

你可以修改 `lib/api.php` 和`templates/setting.php`的代码来添加接口，具体可以参照 8413b272aa8f2efc81e5e2f69975814983c5216e

**Comment by sadk** [comment]
thx
