### ISSUE TITLE
用百度的机器人报错了30000

### ISSUE THREAD

**Issue by ghost** [giuem/TieBaRobot#3]
百度的机器人配置后就成这样的报错，无法回复

![image](https://cloud.githubusercontent.com/assets/3073370/11234533/d27cd3c8-8e03-11e5-9d79-614f89524e0a.png)

![image](https://cloud.githubusercontent.com/assets/3073370/11234571/43c2f7ce-8e04-11e5-9383-0539b0961d3c.png)

**Comment by giuem** [comment]
更换api试试

**Comment by ghost** [comment]
报错不够详细，如果有更详细的报错就好了，比如未知错误太多情况了，可以更细分一些就好了

**Comment by giuem** [comment]
@noinlijin 那是百度返回的错误，不是我定义的
