### ISSUE TITLE
cron不执行啊

### ISSUE THREAD

**Issue by lsblk** [giuem/TieBaRobot#5]
我设置了cron，但不执行，在浏览器中输入网址可以执行，cron代码为\* \* \* \* \* /home/wwwroot/*/cron.php

**Comment by giuem** [comment]
`* * * * * php /home/wwwroot/*/cron.php` 改成这样试试

**Comment by doudouyaer** [comment]
今天搭建的，一切都很顺利。只是回复的时候只有小尾巴没有别的内容。。。换了api也不行。。。
